# 1.Find out all the types of error that we have encountered in our lecture and why? Also include the examples.

A. case sensetivity:

In [2]:
TEN = 10
ten = 20
print(Ten)

NameError: ignored

In [3]:
TEN = 10
ten = 20
print(ten)

20

B. We can't change an empty string to any datatype

In [4]:
# empty string to int
A = ""
print(f"data type before: {type(A)}, value of A: {A}")
A = int(A)
print(f"data type after: {type(A)}, value of A: {A}")

data type before: <class 'str'>, value of A:

ValueError: ignored

 c. we put exact mentioned datatype's value.

In [5]:
A = float(input("Enter value of A: "))
B = int(input("Enter value of B: ")) # 10.2 is float but converting to int

print(f"Sum of A and B is: {A+B}")

Enter value of A: 23.12
Enter value of B: 12.5

ValueError: ignored

In [6]:
A = float(input("Enter value of A: "))
B = int(input("Enter value of B: ")) # 10.2 is float but converting to int

print(f"Sum of A and B is: {A+B}")  # right aproach

Enter value of A: 10.3
Enter value of B: 20
Sum of A and B is: 30.3

D. We should not use reserved words as variable names

In [7]:
rint("Hi there")

print = "Hi there" # as a variable
type(print)

print("Hi there")   #print is reserved word

NameError: ignored

2. Take input A and B and print their sum, mul, div, square of the nos.

In [8]:
a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))

# mathematical equations
sum = a + b
mul = a * b
div = a / b
square = a ** 2

print()

# printing the results
print(f"The 'sum' of {a} & {b} is: {sum}")
print(f"The 'mul' of {a} & {b} is: {mul}")
print(f"The 'div' of {a} & {b} is: {div}")
print(f"The 'square' of {a} & {b} is: {square}")

Enter 1st number: 15
Enter 2nd number: 10

The 'sum' of 15 & 10 is: 25
The 'mul' of 15 & 10 is: 150
The 'div' of 15 & 10 is: 1.5
The 'square' of 15 & 10 is: 225

# 3. How many reserve keywords are there in python and why we should not use them as a variable name.

- There are only 33 reserve keywords in python.
- We shouldn't use those as variable name because if I will use those words as variable, then those might revert in the data type of the variable, and for future use of those variable as keywords, will through an error.

# 4. Create email ids with the user inputs. in the following format - lastname.firstname@gmail.com

In [1]:
first_name = input("Enter the first name: ")
last_name = input("Enter the last name: ")
print(f"The user email id is: {last_name}.{first_name}@gmail.com")

Enter the first name: durgesh
Enter the last name: yogi
The user email id is: yogi.durgesh@gmail.com

# 5. Try to print the following lines -
- Hi I'm Sunny
- My address is 22\3
- I earn 20$ daily.
[ ]

In [2]:
line_1 = "Hi I'm Sunny"
line_2 = "My address is 22\\3"
line_3 = "I earn 20$ daily."

# printing the statements
print(f"The 1st line is: {line_1}")
print(f"The 2nd line is: {line_2}")
print(f"The 3rd line is: {line_3}")

The 1st line is: Hi I'm Sunny
The 2nd line is: My address is 22\3
The 3rd line is: I earn 20$ daily.

# 6. Take user input (name, address, date of birth etc) to fill a form for your college and print their email IDs

In [2]:
first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")

house_no = input("Enter your house_no: ")
city = input("Enter your Village/City name: ")
po = input("Enter your Post Office: ")
pin = input("Enter your Postal Code: ")
dist = input("Enter your District: ")
state = input("Enter your State: ")

dob = input("Enter your date of birth: ")

# printing the outputs
print(f"\nYour full name: {first_name} {last_name}")



print(f"""Your full address:- 
house_no: {house_no},
Post Office: {po},
Postal Code: {pin},
District: {dist},
State: {state}""")

print(f"Your D.O.B. is: {dob}")

# mail id
print(f"The user email id is: {(last_name.lower())}.{(first_name.lower())}@gmail.com")

Enter your first name: Durgesh
Enter your last name: yogi
Enter your house_no: 215
Enter your Village/City name: Bina
Enter your Post Office: bina
Enter your Postal Code: 470113
Enter your District: sagar
Enter your State: madhya pradesh
Enter your date of birth: 14/07/1990

Your full name: Durgesh yogi
Your full address:-
house_no: 215,
Post Office: bina,
Postal Code: 470113,
District: sagar,
State: madhya pradesh
Your D.O.B. is: 14/07/1990
The user email id is: yogi.durgesh@gmail.com

7. Convert the following -

- "22.4" into integer

- "22" into complex no.

In [4]:
# float to integer
x = 12.3
print(f"The data type of given number is: {type(x)}, value of x: {x}")
x = int(x)
print(f"After converting '12.3' into integer: {x}")

print()

The data type of given number is: <class 'float'>, value of x: 12.3
After converting '12.3' into integer: 12

In [5]:
# integer to float
y = 12
print(f"The data type of given number is: {type(y)}, value of x: {y}")
y = float(y)
print(f"After converting '12' into float: {y}")

The data type of given number is: <class 'int'>, value of x: 12
After converting '12' into float: 12.0